### ISSUE TITLE
missing subfolder

### ISSUE THREAD

**Issue by chenblueridge** [jgunthorpe/cloud_mdir_sync#1]
I have some subfolders in my outlook inbox. When I sync the mailbox, the subfolders are not synced.

**Comment by jgunthorpe** [comment]
Each folder must be specified in the config file, outlook treats them all distinctly even if they are subfolders.

**Comment by chenblueridge** [comment]
Thanks. My cms.cfg must be wrong then. Can you provide an example? I tried to add a new line for each folder as a new mail box but outlook365 returned errors. 

BTW. Thanks for your effort to create such a great tool!

**Comment by jgunthorpe** [comment]
If I recall you have to get the right folder name for things to work, something like this will print all the valid folder data, use displayName in the configuration file

```
--- a/cloud_mdir_sync/office365.py
+++ b/cloud_mdir_sync/office365.py
@@ -536,6 +536,8 @@ class O365Mailbox(mailbox.Mailbox):
         self.loop = cfg.loop
         self.name = f"{self.graph.name}:{self.mailbox}"
 
+        print(await self.graph.get_json("v1.0", "/me/mailFolders"))
+
         json = await self.graph.get_json(
             "v1.0",
             f"/me/mailFolders",
```

**Comment by chenblueridge** [comment]
I checked the graph API reference, there is a separate API to list subfolders in a folder.   "/me/mailFolders/{self.Inbox_id}/childFolders",. 

I did a dirty hack for my own usage 

```
+        if len(json["value"]) != 1:
+            json = await self.graph.get_json(
+                "v1.0",
+                f"/me/mailFolders/{self.Inbox_id}/childFolders",
+                params={"$filter": f"displayName eq '{self.mailbox}'"})
+            if len(json["value"]) != 1:
+                raise ValueError(f"Invalid mailbox name {self.mailbox!r}")
+        self.json = json["value"][0]

```

**Comment by jgunthorpe** [comment]
Oh I see, so you have break up the folder path and issue all these queries?
