### ISSUE TITLE
multiple accounts

### ISSUE THREAD

**Issue by us91** [jgunthorpe/cloud_mdir_sync#4]
I am running multiple local accounts and would like to access different cloud accounts using the program. However this does not seem to be easily done through configuration, other than changing the source code by setting a different port for each account. Without manual source code change, the port 8080 would conflict between different accounts.

Request: it would be great if the program can allow the local port to be configurable.

**Comment by jgunthorpe** [comment]
Multiple accounts are supported in a single instance of the program

Just instantiate multiple XX_Account() things and downstream mailboxes. It runs them all concurrently.

**Comment by us91** [comment]
That is a great feature, and I am using it.

The situation I described above is slightly different. I use different local users for different accounts. These users are supposedly separated. So one user does not see another user's files. For that I need to run two instances of cloud-mdir-sync at two different ports. It would still be nice to have the port number to configurable, rather than having to modify the source code to achieve that.

**Comment by jgunthorpe** [comment]
Oh I see, what should happen is the code just allocates a port for itself if it cannot get 8080, or a configurable port I guess

IIRC you can set the port by importing oauth then doing

oauth.WebServer.url = "http://127.0.0.1:8082/"

Inside the config file

**Comment by us91** [comment]
This solution works well. What I did was slightly different:
```
from cloud_mdir_sync import oauth
oauth.WebServer.url = "http://127.0.0.1:8082/"
```

Thank you!
